### ISSUE TITLE
Some issue in RandomSpacePanel.php

### ISSUE THREAD

**Issue by Vatarus** [WASasquatch/humhub-modules-random-space#1]
RandomSpaceModuel.base - should be changed to RandomSpaceModule.base

Otherwise, the language keys do not work.
I fix it + add russian language (see attachment)
png = zip (just rename extention)
![messages](https://cloud.githubusercontent.com/assets/3394915/6241358/f6e5b698-b75e-11e4-961b-4e8a4fb3bf01.png)
![views](https://cloud.githubusercontent.com/assets/3394915/6241360/fc8f4b68-b75e-11e4-81df-5cd21f6f9968.png)

**Comment by WASasquatch** [comment]
Hey, thanks for noticing that, I was actually noticing that while translating a Deutsch version and didn't notice that was the cause. Can you not make pull requests? Is that a option I am overlooking?
