### ISSUE TITLE
Issue: Undefined variable: membershipText

### ISSUE THREAD

**Issue by Vatarus** [WASasquatch/humhub-modules-random-space#2]
Hi,
New issue: **All users except administrator sometimes get this error:**

![issue_randomspace2](https://cloud.githubusercontent.com/assets/3394915/6339893/480c645c-bbfd-11e4-8a62-81fe1933ec5f.png)

**Humhub Report:**

Undefined variable: membershipText (/var/www/html/protected/modules/randomspace/widgets/views/RandomSpacePanel.php:87) Stack trace: #0 /var/www/html/protected/vendors/yii/web/widgets/CWidget.php(244): RandomSpaceSidebarWidget->renderFile() #1 /var/www/html/protected/modules/randomspace/widgets/RandomSpaceSidebarWidget.php(26): RandomSpaceSidebarWidget->render() #2 /var/www/html/protected/vendors/yii/web/CBaseController.php(167): RandomSpaceSidebarWidget->run() #3 /var/www/html/protected/widgets/StackWidget.php(94): DashboardController->widget() #4 /var/www/html/protected/vendors/yii/web/CBaseController.php(173): DashboardSidebarWidget->run() #5 /var/www/html/themes/miafam/views/dashboard/dashboard/index.php(29): DashboardController->widget() #6 /var/www/html/protected/vendors/yii/web/CBaseController.php(126): require() #7 /var/www/html/protected/vendors/yii/web/CBaseController.php(95): DashboardController->renderInternal() #8 /var/www/html/protected/vendors/yii/web/CController.php(869): DashboardController->renderFile() #9 /var/www/html/protected/components/Controller.php(198): DashboardController->renderPartial() #10 /var/www/html/protected/vendors/yii/web/CController.php(782): DashboardController->renderPartial() #11 /var/www/html/protected/modules_core/dashboard/controllers/DashboardController.php(64): DashboardController->render() #12 /var/www/html/protected/vendors/yii/web/actions/CInlineAction.php(49): DashboardController->actionIndex() #13 /var/www/html/protected/vendors/yii/web/CController.php(308): CInlineAction->runWithParams() #14 /var/www/html/protected/vendors/yii/web/filters/CFilterChain.php(133): DashboardController->runAction() #15 /var/www/html/protected/vendors/yii/web/filters/CFilter.php(40): CFilterChain->run() #16 /var/www/html/protected/vendors/yii/web/CController.php(1145): CAccessControlFilter->filter() #17 /var/www/html/protected/vendors/yii/web/filters/CInlineFilter.php(58): DashboardController->filterAccessControl() #18 /var/www/html/protected/vendors/yii/web/filters/CFilterChain.php(130): CInlineFilter->filter() #19 /var/www/html/protected/vendors/yii/web/CController.php(291): CFilterChain->run() #20 /var/www/html/protected/vendors/yii/web/CController.php(265): DashboardController->runActionWithFilters() #21 /var/www/html/protected/vendors/yii/web/CWebApplication.php(282): DashboardController->run() #22 /var/www/html/protected/vendors/yii/web/CWebApplication.php(141): WebApplication->runController() #23 /var/www/html/protected/vendors/yii/base/CApplication.php(180): WebApplication->processRequest() #24 /var/www/html/index.php(39): WebApplication->run() REQUEST_URI=/dashboard in /var/www/html/protected/modules/randomspace/widgets/views/RandomSpacePanel.php (87) in /var/www/html/protected/modules/randomspace/widgets/RandomSpaceSidebarWidget.php (26) in /var/www/html/protected/widgets/StackWidget.php (94) in /var/www/html/themes/miafam/views/dashboard/dashboard/index.php (29) in /var/www/html/protected/components/Controller.php (198)

**Comment by WASasquatch** [comment]
I'm not exactly certain since I have no active usebase to compare, but it may be a private space which is being displayed. Should probably hide those with a edited db search. In the meantime you can add `$membershipText = '';` to the top of the view. I will do some testing soon.

**Comment by Vatarus** [comment]
Well, I added $membershipText = ''; to the top of the view.
The problem solved.
Thanks.

**Comment by WASasquatch** [comment]
Yeah, I think it's simply because under the circumstances of some spaces set to private, or not joining abilities, it would not ever set a variable, which is of course being called in the modules view so something needs to be set. Thanks for catching that. I'm not sure if there is just a simple 'private' flag for spaces, haven't looked but I am assuming not, so I will wait to add that functionality until spaces are more evolved. 

I have added the empty variable to source.
