### ISSUE TITLE
The module does not work in the latest version humhub

### ISSUE THREAD

**Issue by Vatarus** [WASasquatch/humhub-modules-random-space#3]
Hi.

After activating the module there is a problem with the display dashboard streem. See screenshot.

![randomspace_issue](https://cloud.githubusercontent.com/assets/3394915/7266668/263d6660-e8e8-11e4-80d3-1c0198aa8868.png)
There are no errors in the log of the humhub.
In apache error log:
![randomspace_issue01](https://cloud.githubusercontent.com/assets/3394915/7266701/ce83bf68-e8e8-11e4-8964-5940e31a3d4d.png)

**Comment by WASasquatch** [comment]
How many spaces do you have?

**Comment by Vatarus** [comment]
two spaces on local host

**Comment by Vatarus** [comment]
Sorry. Not carefully read the requirements.
**At least 5 Public Spaces**

**Comment by OataO** [comment]
I have more than 5 spaces and it didn't works anymore :) 
![image 215](https://cloud.githubusercontent.com/assets/12020657/7437886/3749b046-f05c-11e4-9b45-56cd2f7be976.png)

**Comment by WASasquatch** [comment]
This error indicates that the directory `protected/modules/randomspace/` or the file `RandomSpaceModule.php` doesn't exist in the system, or is not readable (CHMOD)

**Comment by OataO** [comment]
I'm pretty sure i have all requierments :) i tried online and in local mode . it's the same chmod is good and files are here.
![image 216](https://cloud.githubusercontent.com/assets/12020657/7440772/c19865f6-f0c7-11e4-90b5-609455672244.png)

**Comment by OataO** [comment]
Anyway the module is activated . But can't load dashboard 
![image 217](https://cloud.githubusercontent.com/assets/12020657/7440793/40b52b38-f0ca-11e4-99d7-ebfdc29d2bd2.png)

And this message is in log files

**Comment by OataO** [comment]
OK in fact i have no error in logging. But i can't load dashboard when i active module

**Comment by OataO** [comment]
Same problem as vatarus.

**Comment by WASasquatch** [comment]
> Sorry. Not carefully read the requirements.
> **At least 5 Public Spaces**

How many spaces do you have?

**Comment by OataO** [comment]
27 
![image 229](https://cloud.githubusercontent.com/assets/12020657/7453573/e4c697ce-f26a-11e4-9803-b86a5b95c437.png)

**Comment by WASasquatch** [comment]
I'm sorry. Please ensure you are installing the module correctly. It works fine, even with one space.

<img src="http://i.imgur.com/KDCMxYP.png" />

> ### Installation
> - Drop into your /protected/modules folder as **randomspace**
> - Activate module in ACP
