### ISSUE TITLE
Not work to 0.11.2

### ISSUE THREAD

**Issue by jus61** [WASasquatch/humhub-modules-random-space#4]
![dawdwadwad](https://cloud.githubusercontent.com/assets/2851948/7785699/56cb0a7c-019c-11e5-9941-2fe16775be5e.png)

I hav HumHub 0.11.2

**Comment by WASasquatch** [comment]
https://github.com/WASasquatch/humhub-modules-random-space/issues/3

This is a random space module picking a random space. In general it is slow, prone to bugs, and errors. Without actual errors codes I cannot provide you any support at all. Check your Apache/PHP logs.

**Comment by jus61** [comment]
Trying to get property of non-object

/protected/modules/randomspace/widgets/RandomSpaceSidebarWidget.php(45)

 /**
36      \* Get a random space model from DB
37      *
38      \* @return array of space and membership information from Space Model.
39      */
40     private function getRandomSpace() {
41  
42         $max = Space::model()->count();
43         $randId = rand(0,$max);
44         $space = Space::model()->find(array('offset'=>$randId));
45         if ($space->attributes['visibility'] == 2) {
46             if ( is_object($space) ) {
47                     $members = array();
48                 $membership = Yii::app()->db->createCommand()
49                         ->select('user_id')
50                     ->from('space_membership')
51                     ->where('space_id=:id', array(':id'=>$space->id))
52                     ->queryAll();
53                 foreach ( $membership as $member ) {
54                     $members[] = User::model()->findByPk($member['user_id']);
55                 }
56                 return array($space, $members);
57             // Something went wrong.. try again

/protected/modules/randomspace/widgets/RandomSpaceSidebarWidget.php(20): RandomSpaceSidebarWidget->getRandomSpace()
- @render random space widget
  16      */
  17     public function run() {
  18         $css = Yii::app()->assetManager->publish(dirname(**FILE**) . '/../css', true, 0, defined('YII_DEBUG'));
  19         Yii::app()->clientScript->registerCssFile($css . '/randomspace.css');
  20         $spaceInfo = $this->getRandomSpace();
  21         if ( is_object($spaceInfo[0]) && is_array($spaceInfo[1]) ) {
  22             $this->render ( 'RandomSpacePanel', array (
  23                 'css' => $css,
  24                 'space' => $spaceInfo[0],
  25                 'members' => $spaceInfo[1]

**Comment by WASasquatch** [comment]
Update to latest source, not release

https://github.com/WASasquatch/humhub-modules-random-space/blob/master/widgets/RandomSpaceSidebarWidget.php
